# Generated by Django 2.1 on 2018-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20181008_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderProduct',
            field=models.ManyToManyField(to='store.OrderProduct'),
        ),
        migrations.AlterIndexTogether(
            name='order',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
