# Generated by Django 2.1 on 2018-10-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20181008_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='bought',
            new_name='ordered',
        ),
        migrations.AddField(
            model_name='cart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
