# Generated by Django 2.1 on 2018-10-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='img',
            field=models.ImageField(default='', upload_to='media/', verbose_name='imagem apresentacao'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(default='', max_length=200),
        ),
    ]
