version: '3'

services:
  db:
    image: nouchka/sqlite3
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000 #--settings "Projeto_loja.settings"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
